language: c

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - LISP=sbcl-bin/2.0.0
    - GH_REPO=sbcl_bin

jobs:
    include:
      - os: linux
        env: ARCH=x86
        addons:
          apt:
            packages:
              - lib32z1-dev
              - gcc-multilib
      - os: linux
        arch: arm64
        env: ARCH=arm64
        addons:
          apt:
            packages:
              - libcurl4-openssl-dev
      - os: linux
        services: docker
        env:
          - ARCH=x86-64
          - SUFFIX=-glibc2.10
          - LINKFLAGS=-lrt
          - DOCKER=docker.pkg.github.com/roswell/sbcl_bin/glibc2.10-sbcl1.5.7:1
      - os: linux
        services: docker
        env:
          - ARCH=x86
          - SUFFIX=-glibc2.10
          - LINKFLAGS=-lrt
          - DOCKER=docker.pkg.github.com/roswell/sbcl_bin/glibc2.10-sbcl1.5.7:1
      #- os: linux-ppc64le
      #  env: TARGET=ppc64le LISP=sbcl-bin/1.5.8

cache:
  directories:
    - $HOME/.roswell

install:
  - if [ -n "$DOCKER" ]; then
       docker login docker.pkg.github.com -u snmsts -p $GITHUB_OAUTH_TOKEN;
       docker pull $DOCKER;
    fi
  - $SETARCH curl -L https://raw.githubusercontent.com/roswell/roswell/$ROSWELL_BRANCH/scripts/install-for-ci.sh | sh
  - $SETARCH ros install snmsts/sn.github

script:
  - if [ -n "$DOCKER" ]; then
      make docker;
      make latest-version docker;
    else
      $SETARCH make latest-version archive;
    fi
after_success:
  - $SETARCH make latest-version upload-archive
