name: docker-build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [glibc2.19-sbcl2.0.0]
    environment: SET_VERSION

    steps:
      - uses: actions/checkout@v2
      - name: build
        env:
          IMAGE: ${{ matrix.image }}
        run: |
          docker build tools-for-build/$IMAGE/
