name: linux

on:
  schedule:
    - cron:  '0 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        lisp: [sbcl-bin/2.0.0]
        target: [x86-64, x86]
    environment: SET_VERSION

    steps:
      - uses: actions/checkout@v2

      - name: setenv
        run: |
          echo "$HOME/.roswell/bin" >> $GITHUB_PATH
          echo "ROSWELL_BRANCH=master" >> $GITHUB_ENV
          echo "ROSWELL_INSTALL_DIR=$HOME/.roswell" >> $GITHUB_ENV
          echo "DOCKER=docker.pkg.github.com/roswell/sbcl_bin/glibc2.19-sbcl2.0.0:1" >> $GITHUB_ENV

      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt-get -y install git build-essential automake libcurl4-openssl-dev lib32z1-dev gcc-multilib
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          ros install snmsts/sn.github
          if [ -n "$DOCKER" ]; then
             docker login docker.pkg.github.com -u snmsts -p $GITHUB_OAUTH_TOKEN;
             docker pull $DOCKER;
          fi
      - name: build
        env:
          VERSION: ${{ secrets.VERSION }}
          TARGETS: ${{ matrix.target }}
        run: |
          if [ "$VERSION" = "" ]; then
            make latest-version docker;
          else
            make docker;
          fi
      - name: upload
        env:
          VERSION: ${{ secrets.VERSION }}
          GITHUB_OAUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCH: ${{ matrix.target }}
        run: |
          if [ "$VERSION" = "" ]; then
            make latest-version upload-archive;
          else
            make upload-archive;
          fi
